#!/usr/bin/env python
"""
scripts/plot_combined_confusion.py

Figure 3: Row-normalized confusion matrix for the combined-feature
3-class logistic regression model.

Reads from results/temporal_experiment/metrics/combined__3class__logreg.json
(already generated by run_temporal_experiment.py).

Output:
    results/figures/confusion_3class_combined_logreg.png
    results/figures/confusion_3class_combined_logreg.pdf
"""

from __future__ import annotations
import json
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

METRICS_JSON = Path(
    "results/temporal_experiment/metrics/combined__3class__logreg.json"
)
OUT_DIR = Path("results/figures")

CLASS_DISPLAY = {
    "control":       "Control",
    "depression":    "Depression",
    "schizophrenia": "Schizophrenia",
}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with open(METRICS_JSON) as f:
        metrics = json.load(f)

    cm_data = metrics["confusion_matrix"]
    labels_raw = cm_data["labels"]
    matrix = np.array(cm_data["matrix"])
    labels = [CLASS_DISPLAY.get(l, l) for l in labels_raw]

    fig, ax = plt.subplots(figsize=(5.5, 4.8))
    fig.patch.set_facecolor("white")

    im = ax.imshow(
        matrix, cmap="Blues",
        vmin=0.0, vmax=1.0,
        aspect="equal",
    )

    # Cell annotations
    for i in range(len(labels)):
        for j in range(len(labels)):
            val = matrix[i, j]
            text_color = "white" if val > 0.60 else "#222222"
            ax.text(
                j, i, f"{val:.2f}",
                ha="center", va="center",
                fontsize=13, fontweight="bold",
                color=text_color,
            )

    ax.set_xticks(range(len(labels)))
    ax.set_yticks(range(len(labels)))
    ax.set_xticklabels(labels, fontsize=10)
    ax.set_yticklabels(labels, fontsize=10)
    ax.set_xlabel("Predicted label", fontsize=10, labelpad=8, color="#444444")
    ax.set_ylabel("True label", fontsize=10, labelpad=8, color="#444444")

    ax.set_title(
        "3-class confusion matrix — combined features, logistic regression\n"
        f"Macro-F1 = {metrics['macro_f1']:.3f}  "
        f"(95% CI {metrics['ci_low']:.3f}–{metrics['ci_high']:.3f})",
        fontsize=9.5, color="#444444", pad=12, fontweight="normal",
    )

    # Colorbar
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("Recall (row-normalized)", fontsize=9, color="#555555")
    cbar.ax.tick_params(labelsize=8)
    cbar.outline.set_edgecolor("#CCCCCC")

    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.tick_params(axis="both", length=0)

    plt.tight_layout()

    for fmt in ("png", "pdf"):
        path = OUT_DIR / f"confusion_3class_combined_logreg.{fmt}"
        fig.savefig(
            path,
            dpi=180 if fmt == "png" else None,
            bbox_inches="tight",
            facecolor="white",
        )
        print(f"Saved: {path}")

    plt.close()


if __name__ == "__main__":
    main()